spring:
  application:
    name: BE_DATN
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=QUANLYVOTCAULONG;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: vietphan0925@gmail.com
    password: rvhsceruswmjadzj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
groq:
  api:
    key: 
server:
  port: 8080
vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: RCNI8KWJ
  hash-secret: TVQNBFVNRCSQPMRDEGNTPMMFJNABJZZR
  return-url: http://localhost:8080/cua-hang/vnpay/return
  bank-code: NCB
